### ISSUE TITLE
Error taking screenshot of login screen

### ISSUE THREAD

**Issue by simonw** [simonw/django-screenshots#2]
Seeing this in GitHub Actions:
```
Error: Page.evaluate: TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at eval (eval at evaluate (:234:30), <anonymous>:11:23)
    at Array.forEach (<anonymous>)
    at eval (eval at evaluate (:234:30), <anonymous>:10:9)
    at new Promise (<anonymous>)
    at eval (eval at evaluate (:234:30), <anonymous>:1:1)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:234:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
Traceback (most recent call last):
  File "/home/runner/work/django-screenshots/django-screenshots/generate.py", line 29, in <module>
    subprocess.run([
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['shot-scraper', 'multi', 'shots.yml']' returned non-zero exit status 1.
```

**Comment by simonw** [comment]
I'm going to disable this for the moment to get the first run to work.

Refs #1

**Comment by simonw** [comment]
![image](https://github.com/user-attachments/assets/936226ec-58cf-4477-a149-b1e462ce26bc)

**Comment by michu8583-byte12** [comment]
> Seeing this in GitHub Actions:
> 
> ```
> Error: Page.evaluate: TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
>     at eval (eval at evaluate (:234:30), <anonymous>:11:23)
>     at Array.forEach (<anonymous>)
>     at eval (eval at evaluate (:234:30), <anonymous>:10:9)
>     at new Promise (<anonymous>)
>     at eval (eval at evaluate (:234:30), <anonymous>:1:1)
>     at eval (<anonymous>)
>     at UtilityScript.evaluate (<anonymous>:234:30)
>     at UtilityScript.<anonymous> (<anonymous>:1:44)
> Traceback (most recent call last):
>   File "/home/runner/work/django-screenshots/django-screenshots/generate.py", line 29, in <module>
>     subprocess.run([
>   File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['shot-scraper', 'multi', 'shots.yml']' returned non-zero exit status 1.
> ```
